export const QUESTIONS_FETCH_REQUESTED = "QUESTIONS_FETCH_REQUESTED";
export const QUESTIONS_FETCH_SUCCEEDED = "QUESTIONS_FETCH_SUCCEEDED";
export const QUESTIONS_FETCH_FAILED = "QUESTIONS_FETCH_FAILED";
